// GENERATED by scripts/build-content.py from seo-baseline/ (the SEO baseline of 2026-10-04). Edit with care:
// every value here is what the live WordPress site emits today, and the SEO check compares against it.
export type PageKind = "home" | "page" | "project" | "post";

export interface SeoEntry {
  kind: PageKind;
  title: string;
  description: string;
  canonical: string;
  ogTitle: string;
  ogDescription: string;
  /** Absolute URL, exactly as in the baseline (files under /wp-content/uploads/ ship in public/). */
  ogImage: string;
  h1: string;
  published: string;
  modified: string;
  /** The primary image of the page, for the JSON-LD graph. */
  image: { url: string; width: number; height: number; caption: string } | null;
  breadcrumb: { name: string; path?: string }[];
  article?: { wordCount: number; keywords: string[]; section: string[] };
}

export const seo: Record<string, SeoEntry> = {
  "/": {
    "kind": "home",
    "title": "Formwork Design Services | Layouts, BOQ & Pour Sequences",
    "description": "Formwork and shoring design for concrete structures - buildable layouts, quantified BOQs and pour sequences. 50+ projects across the US, Canada and Australia.",
    "canonical": "https://formworkforconcrete.com/",
    "ogTitle": "Formwork Design Services for Concrete Structures",
    "ogDescription": "Formwork and shoring design for concrete structures - buildable layouts, quantified BOQs and pour sequences. 50+ projects across the US, Canada and Australia.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/09/formwork-concrete-formwork-detailing-jpg.webp",
    "h1": "Formwork Design That Keeps Your Pour on Schedule",
    "published": "2023-07-04T12:54:08+00:00",
    "modified": "2025-07-06T03:14:52+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/09/formwork-concrete-formwork-detailing-jpg.webp",
      "width": 727,
      "height": 582,
      "caption": "Detailed 3D formwork design for complex industrial concrete structure"
    },
    "breadcrumb": [
      {
        "name": "Home"
      }
    ]
  },
  "/contact-us/": {
    "kind": "page",
    "title": "Contact Us - Formwork for concrete",
    "description": "Get in touch with us for all your concrete formwork design needs. Whether you're working on foundations, walls, slabs, or complex structures, our team is here to provide expert solutions",
    "canonical": "https://formworkforconcrete.com/contact-us/",
    "ogTitle": "Contact Us",
    "ogDescription": "Get in touch with us for all your concrete formwork design needs. Whether you're working on foundations, walls, slabs, or complex structures, our team is here to provide expert solutions",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/house-or-villa-under-construction-using-modern-tec-min-scaled.webp",
    "h1": "Reach Out for a Free Consultation and Quote",
    "published": "2023-07-31T12:46:51+00:00",
    "modified": "2025-03-12T05:20:01+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/house-or-villa-under-construction-using-modern-tec-min-scaled.webp",
      "width": 2560,
      "height": 1707,
      "caption": "House under construction using modern formwork techniques"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Contact Us"
      }
    ]
  },
  "/designing-formwork-for-concrete-with-wood-lumber-panels/": {
    "kind": "post",
    "title": "Designing Formwork for Concrete with Wood Lumber and Panels",
    "description": "Discover how to design formwork for concrete using wood lumber and panels, plus expert formwork design services for efficient construction.",
    "canonical": "https://formworkforconcrete.com/designing-formwork-for-concrete-with-wood-lumber-panels/",
    "ogTitle": "How to Design Formwork for Concrete Using Wood Lumber and Panels",
    "ogDescription": "Discover how to design formwork for concrete using wood lumber and panels, plus expert formwork design services for efficient construction.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/handmade-scaffolding-with-wooden-beams-and-bars-in-min-scaled.jpg",
    "h1": "How to Design Formwork for Concrete Using Wood Lumber and Panels",
    "published": "2024-10-10T11:11:00+00:00",
    "modified": "2025-07-06T04:14:31+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/handmade-scaffolding-with-wooden-beams-and-bars-in-min-scaled.jpg",
      "width": 2560,
      "height": 1706,
      "caption": "Design layout of concrete formwork made from wood lumber and plywood panels"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "How to Design Formwork for Concrete Using Wood Lumber and Panels"
      }
    ],
    "article": {
      "wordCount": 971,
      "keywords": [
        "Concrete Construction Services",
        "Concrete Formwork Design",
        "Construction Design Services",
        "Construction Support Services",
        "Custom Concrete Solutions",
        "Custom Formwork Solutions",
        "Engineering Design Services",
        "Expert Formwork Design",
        "Formwork Consulting",
        "Formwork Design Services",
        "Formwork Planning and Design",
        "Professional Formwork Design",
        "Structural Design Services",
        "Structural Engineering Services",
        "Temporary Structure Design"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/find-expert-formwork-engineers-and-designers-for-your-project/": {
    "kind": "post",
    "title": "Hire Expert Formwork Engineers & Designers",
    "description": "Formwork design for soffits, walls and capping beams using Peri, Doka and Titan systems, with detailed layouts and estimating support for your project.",
    "canonical": "https://formworkforconcrete.com/find-expert-formwork-engineers-and-designers-for-your-project/",
    "ogTitle": "Find Expert Formwork Engineers and Designers for Your Project",
    "ogDescription": "Formwork design for soffits, walls and capping beams using Peri, Doka and Titan systems, with detailed layouts and estimating support for your project.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/11/architects-and-engineers-are-working-together-to-e-min-scaled.jpg",
    "h1": "Find Expert Formwork Engineers and Designers for Your Project",
    "published": "2024-11-19T08:43:15+00:00",
    "modified": "2025-07-06T04:03:30+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/11/architects-and-engineers-are-working-together-to-e-min-scaled.jpg",
      "width": 2560,
      "height": 1707,
      "caption": "formwork-design-service"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Find Expert Formwork Engineers and Designers for Your Project"
      }
    ],
    "article": {
      "wordCount": 333,
      "keywords": [
        "#BIM",
        "#BuildingDesign",
        "#Concrete",
        "#ConcreteConstruction",
        "#ConstructionDrawings",
        "#ConstructionJoints",
        "#ConstructionPlanning",
        "#ConstructionSafety",
        "#Formwork",
        "#FormworkDesign",
        "#ProjectManagement",
        "#QualityControl",
        "#ShopDrawings",
        "#StructuralEngineering",
        "Construction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/formwork-design-for-a-suspended-concrete-slab/": {
    "kind": "post",
    "title": "Formwork Design for a Suspended Concrete Slab",
    "description": "Key components, load calculations and deflection control for suspended slab formwork: decking, props, beams and joists explained by our engineers.",
    "canonical": "https://formworkforconcrete.com/formwork-design-for-a-suspended-concrete-slab/",
    "ogTitle": "Formwork Design for a Suspended Concrete Slab",
    "ogDescription": "Key components, load calculations and deflection control for suspended slab formwork: decking, props, beams and joists explained by our engineers.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-supports-the-second-floor-of-a-monolithic-min-scaled.webp",
    "h1": "Formwork Design for a Suspended Concrete Slab",
    "published": "2024-11-04T09:39:31+00:00",
    "modified": "2024-11-04T09:49:43+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-supports-the-second-floor-of-a-monolithic-min-scaled.webp",
      "width": 2560,
      "height": 1707,
      "caption": "Expert formwork design services for robust concrete construction"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Formwork Design for a Suspended Concrete Slab"
      }
    ],
    "article": {
      "wordCount": 535,
      "keywords": [
        "#BIM",
        "#BuildingDesign",
        "#Concrete",
        "#ConcreteConstruction",
        "#ConstructionDrawings",
        "#ConstructionJoints",
        "#ConstructionPlanning",
        "#ConstructionSafety",
        "#Formwork",
        "#FormworkDesign",
        "#ProjectManagement",
        "#QualityControl",
        "#ShopDrawings",
        "#StructuralEngineering",
        "Construction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/formwork-shop-drawings-and-construction-joint-layout/": {
    "kind": "post",
    "title": "Formwork Shop Drawings & Construction Joint Layout Guide",
    "description": "How formwork shop drawings and construction joint layouts work together to protect structural integrity, control pour phasing and cut costly rework.",
    "canonical": "https://formworkforconcrete.com/formwork-shop-drawings-and-construction-joint-layout/",
    "ogTitle": "Formwork Shop Drawings and Construction Joint Layout",
    "ogDescription": "How formwork shop drawings and construction joint layouts work together to protect structural integrity, control pour phasing and cut costly rework.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-concrete-design-pourmap-2.jpg",
    "h1": "Formwork Shop Drawings and Construction Joint Layout",
    "published": "2024-10-16T10:26:01+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-concrete-design-pourmap-2.jpg",
      "width": 842,
      "height": 595,
      "caption": "Concrete pour map and sequencing plan for formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Formwork Shop Drawings and Construction Joint Layout"
      }
    ],
    "article": {
      "wordCount": 912,
      "keywords": [
        "#BIM",
        "#BuildingDesign",
        "#Concrete",
        "#ConcreteConstruction",
        "#ConstructionDrawings",
        "#ConstructionJoints",
        "#ConstructionPlanning",
        "#ConstructionSafety",
        "#Formwork",
        "#FormworkDesign",
        "#ProjectManagement",
        "#QualityControl",
        "#ShopDrawings",
        "#StructuralEngineering",
        "Construction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/how-to-design-formwork-and-scaffolding-components/": {
    "kind": "post",
    "title": "How to Design Formwork and Scaffolding Components",
    "description": "A five-step method for configuring Doka, PERI and Titan formwork and scaffolding: system selection, panel layout, bracing and pre-pour inspection.",
    "canonical": "https://formworkforconcrete.com/how-to-design-formwork-and-scaffolding-components/",
    "ogTitle": "How to Design Formwork and Scaffolding Components",
    "ogDescription": "A five-step method for configuring Doka, PERI and Titan formwork and scaffolding: system selection, panel layout, bracing and pre-pour inspection.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2025/03/Design-Formwork-and-Scaffolding-Components.jpeg",
    "h1": "How to Design Formwork and Scaffolding Components",
    "published": "2025-03-03T04:28:27+00:00",
    "modified": "2025-03-03T04:40:28+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2025/03/Design-Formwork-and-Scaffolding-Components.jpeg",
      "width": 1024,
      "height": 683,
      "caption": "Design Formwork and Scaffolding Components"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "How to Design Formwork and Scaffolding Components"
      }
    ],
    "article": {
      "wordCount": 481,
      "keywords": [
        "#BIM",
        "#BuildingDesign",
        "#Concrete",
        "#ConcreteConstruction",
        "#ConstructionDrawings",
        "#ConstructionJoints",
        "#ConstructionPlanning",
        "#ConstructionSafety",
        "#Formwork",
        "#FormworkDesign",
        "#ProjectManagement",
        "#QualityControl",
        "#ShopDrawings",
        "#StructuralEngineering",
        "Construction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/news/": {
    "kind": "page",
    "title": "News - Formwork for concrete",
    "description": "Stay updated with the latest insights and news from the world of concrete formwork design.",
    "canonical": "https://formworkforconcrete.com/news/",
    "ogTitle": "News",
    "ogDescription": "Stay updated with the latest insights and news from the world of concrete formwork design.",
    "ogImage": "",
    "h1": "Formwork Design News & Insights",
    "published": "2023-07-31T12:49:56+00:00",
    "modified": "2024-10-24T08:37:34+00:00",
    "image": null,
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "News"
      }
    ]
  },
  "/projects/": {
    "kind": "page",
    "title": "Concrete Formwork Design Projects - Formwork for concrete",
    "description": "Comprehensive Concrete Formwork Design Services: Precision Engineering for Foundations, Walls, Slabs, and Complex Structures",
    "canonical": "https://formworkforconcrete.com/projects/",
    "ogTitle": "Projects",
    "ogDescription": "Comprehensive Concrete Formwork Design Services: Precision Engineering for Foundations, Walls, Slabs, and Complex Structures",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/high-rise-building-under-construction-min-scaled.webp",
    "h1": "Our Works",
    "published": "2023-07-31T12:47:42+00:00",
    "modified": "2025-07-05T18:19:33+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/high-rise-building-under-construction-min-scaled.webp",
      "width": 2560,
      "height": 1707,
      "caption": "Concrete formwork design service"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects"
      }
    ]
  },
  "/projects/ajax-foundation/": {
    "kind": "project",
    "title": "Foundation Formwork Planning & Detailing Services",
    "description": "Foundation formwork planning and detailing for a phased furnace foundation replacement, including system formwork assembly and formwork take-off.",
    "canonical": "https://formworkforconcrete.com/projects/ajax-foundation/",
    "ogTitle": "Ajax Tocco 85 Ton Furnace Foundation",
    "ogDescription": "Foundation formwork planning and detailing for a phased furnace foundation replacement, including system formwork assembly and formwork take-off.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ajax-foundation-concrete-formwork-cover_anloro-jpg.webp",
    "h1": "Ajax Tocco 85 Ton Furnace Foundation",
    "published": "2023-08-02T11:48:00+00:00",
    "modified": "2025-07-06T04:00:25+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ajax-foundation-concrete-formwork-cover_anloro-jpg.webp",
      "width": 891,
      "height": 675,
      "caption": "Ajax Tocco furnace foundation formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Ajax Tocco 85 Ton Furnace Foundation"
      }
    ]
  },
  "/projects/brb-mbr-structure/": {
    "kind": "project",
    "title": "BRB & MBR Structure - Formwork for concrete",
    "description": "Comprehensive formwork design for walls, slabs, beams, and columns, ensuring precision, safety, and durability during concrete pouring",
    "canonical": "https://formworkforconcrete.com/projects/brb-mbr-structure/",
    "ogTitle": "BRB & MBR Structure",
    "ogDescription": "Comprehensive formwork design for walls, slabs, beams, and columns, ensuring precision, safety, and durability during concrete pouring",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/mbr-concrete-formwork_dylwgi-jpg.webp",
    "h1": "BRB & MBR Structure",
    "published": "2024-10-08T10:26:51+00:00",
    "modified": "2024-10-15T04:40:05+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/mbr-concrete-formwork_dylwgi-jpg.webp",
      "width": 1082,
      "height": 771,
      "caption": "BRB and MBR structure formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "BRB & MBR Structure"
      }
    ]
  },
  "/projects/formwork-belle-project/": {
    "kind": "project",
    "title": "Belle Villa Formwork Design on a Sloped Site",
    "description": "Formwork design for a villa on a sloped site, using wood lumber and panel materials to suit the complex geometry of the slab concrete structure.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-belle-project/",
    "ogTitle": "Formwork Belle Projects",
    "ogDescription": "Formwork design for a villa on a sloped site, using wood lumber and panel materials to suit the complex geometry of the slab concrete structure.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ptf_formwork_3d-1-jpg.webp",
    "h1": "Formwork Belle Projects",
    "published": "2024-10-14T08:29:11+00:00",
    "modified": "2024-10-14T08:37:26+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ptf_formwork_3d-1-jpg.webp",
      "width": 2447,
      "height": 2093,
      "caption": "3D formwork model of the Belle villa slab structure"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Formwork Belle Projects"
      }
    ]
  },
  "/projects/formwork-core-walls/": {
    "kind": "project",
    "title": "Elevator Core Wall Formwork Design with Soloform",
    "description": "Core wall formwork design developed from architectural and structural drawings using Soloform, detailed so no additional on-site data is needed.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-core-walls/",
    "ogTitle": "Elevator Walls",
    "ogDescription": "Core wall formwork design developed from architectural and structural drawings using Soloform, detailed so no additional on-site data is needed.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/soloform-concrete-formwork_shp7t0-jpg.webp",
    "h1": "Elevator Walls",
    "published": "2024-10-08T11:28:21+00:00",
    "modified": "2024-10-08T11:50:08+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/soloform-concrete-formwork_shp7t0-jpg.webp",
      "width": 916,
      "height": 717,
      "caption": "Soloform elevator core wall formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Elevator Walls"
      }
    ]
  },
  "/projects/formwork-new-house-doka/": {
    "kind": "project",
    "title": "Doka Slab Formwork Design for a Multi-Story Villa",
    "description": "Formwork design for a new multi-story villa with concrete pouring across multiple floors, using the Doka formwork system as the primary slab solution.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-new-house-doka/",
    "ogTitle": "New House Building",
    "ogDescription": "Formwork design for a new multi-story villa with concrete pouring across multiple floors, using the Doka formwork system as the primary slab solution.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-new-building-doka-3d-jpg.webp",
    "h1": "New House Building",
    "published": "2024-10-14T03:23:54+00:00",
    "modified": "2024-10-14T04:40:00+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-new-building-doka-3d-jpg.webp",
      "width": 842,
      "height": 595,
      "caption": "3D Doka formwork model for the multi-story villa slab"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "New House Building"
      }
    ]
  },
  "/projects/formwork-peitro-carnaghi-foudation/": {
    "kind": "project",
    "title": "Pietro Carnaghi Machine Foundation Formwork Design",
    "description": "Formwork design for a machine foundation built over a partially demolished structure, including Stelcore pile removal and alignment coordination.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-peitro-carnaghi-foudation/",
    "ogTitle": "Pietro Carnaghi Foundation",
    "ogDescription": "Formwork design for a machine foundation built over a partially demolished structure, including Stelcore pile removal and alignment coordination.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/nfpc-concrete-formwork_kdk8fo-jpg.webp",
    "h1": "Pietro Carnaghi Foundation",
    "published": "2024-10-08T10:57:51+00:00",
    "modified": "2024-10-08T11:50:40+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/nfpc-concrete-formwork_kdk8fo-jpg.webp",
      "width": 833,
      "height": 722,
      "caption": "Pietro Carnaghi machine foundation formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Pietro Carnaghi Foundation"
      }
    ]
  },
  "/projects/formwork-preliminary-treatment-facility/": {
    "kind": "project",
    "title": "Preliminary Treatment Facility Formwork Design",
    "description": "Formwork design and panel scheduling for walls, slabs, beams and columns on a two-story preliminary treatment facility, engineered for pour pressures.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-preliminary-treatment-facility/",
    "ogTitle": "Preliminary Treatment Facility",
    "ogDescription": "Formwork design and panel scheduling for walls, slabs, beams and columns on a two-story preliminary treatment facility, engineered for pour pressures.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ptf-concrete-formwork_hmlbfb-jpg.webp",
    "h1": "Preliminary Treatment Facility",
    "published": "2024-10-08T11:09:24+00:00",
    "modified": "2024-10-08T11:49:35+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/ptf-concrete-formwork_hmlbfb-jpg.webp",
      "width": 1014,
      "height": 774,
      "caption": "Preliminary treatment facility formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Preliminary Treatment Facility"
      }
    ]
  },
  "/projects/formwork-spring-creek-auxiliary-foundation/": {
    "kind": "project",
    "title": "Spring Creek Effluent Chamber Formwork Drawings",
    "description": "Formwork design drawings for reconstruction of an effluent chamber structure, with specifications and dimensions for efficient on-site assembly.",
    "canonical": "https://formworkforconcrete.com/projects/formwork-spring-creek-auxiliary-foundation/",
    "ogTitle": "Spring Creek Auxiliary Foundation",
    "ogDescription": "Formwork design drawings for reconstruction of an effluent chamber structure, with specifications and dimensions for efficient on-site assembly.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/wpcp-concrete-formwork_kbjd7q-jpg.webp",
    "h1": "Spring Creek Auxiliary Foundation",
    "published": "2024-10-08T11:35:16+00:00",
    "modified": "2024-10-08T11:40:55+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/wpcp-concrete-formwork_kbjd7q-jpg.webp",
      "width": 940,
      "height": 709,
      "caption": "Spring Creek effluent chamber formwork design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Spring Creek Auxiliary Foundation"
      }
    ]
  },
  "/projects/kyle-dam-foundation/": {
    "kind": "project",
    "title": "Kyle Dam Formwork Design & Gang Form Detailing",
    "description": "Formwork design for two new retaining walls on an existing longitudinal dam slab, using a custom gang form system with cross waterstop detailing.",
    "canonical": "https://formworkforconcrete.com/projects/kyle-dam-foundation/",
    "ogTitle": "Kyle Dam",
    "ogDescription": "Formwork design for two new retaining walls on an existing longitudinal dam slab, using a custom gang form system with cross waterstop detailing.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/kyle-damp-concrete-formwork-min_hwrqaj-jpg.webp",
    "h1": "Kyle Dam",
    "published": "2024-10-08T05:12:51+00:00",
    "modified": "2024-10-08T11:48:52+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/kyle-damp-concrete-formwork-min_hwrqaj-jpg.webp",
      "width": 975,
      "height": 708,
      "caption": "Kyle Dam retaining wall gang form design"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Kyle Dam"
      }
    ]
  },
  "/projects/outlet-spillway-dam/": {
    "kind": "project",
    "title": "Outlet Spillway Dam Formwork Design & Detailing",
    "description": "Formwork design for a complex spillway slab extension with slopes in both directions, using Symons formwork with reinforcement detailing per section.",
    "canonical": "https://formworkforconcrete.com/projects/outlet-spillway-dam/",
    "ogTitle": "Outlet Spillway Dam",
    "ogDescription": "Formwork design for a complex spillway slab extension with slopes in both directions, using Symons formwork with reinforcement detailing per section.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/spillway-overview.png",
    "h1": "Outlet Spillway Dam",
    "published": "2024-10-14T08:52:02+00:00",
    "modified": "2026-08-04T13:30:29+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/spillway-overview.png",
      "width": 758,
      "height": 567,
      "caption": "Overview of the outlet spillway dam structure"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Outlet Spillway Dam"
      }
    ]
  },
  "/projects/pretreatment-structure-foudation-and-intermediate/": {
    "kind": "project",
    "title": "Pretreatment Structure Formwork Detailing & Design",
    "description": "Formwork detailing and design for a water treatment project, covering the foundation, wall and intermediate slab structures.",
    "canonical": "https://formworkforconcrete.com/projects/pretreatment-structure-foudation-and-intermediate/",
    "ogTitle": "Pretreatment Structure Foundation and Intermediate Slab",
    "ogDescription": "Formwork detailing and design for a water treatment project, covering the foundation, wall and intermediate slab structures.",
    "ogImage": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-pretreatment-structure-3d-1-jpg.webp",
    "h1": "Pretreatment Structure Foundation and Intermediate Slab",
    "published": "2024-10-14T09:07:14+00:00",
    "modified": "2026-08-04T13:30:32+00:00",
    "image": {
      "url": "https://formworkforconcrete.com/wp-content/uploads/2024/10/formwork-pretreatment-structure-3d-1-jpg.webp",
      "width": 842,
      "height": 595,
      "caption": "3D formwork model of the pretreatment structure foundation and intermediate slab"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Pretreatment Structure Foundation and Intermediate Slab"
      }
    ]
  },
  // Added after the migration (2026-10-08): new project pages and posts, not part of the WordPress baseline.
  "/projects/fm-woods-wtp-wall-formwork/": {
    "kind": "project",
    "title": "F.M. Woods WTP Wall Formwork Drawings by Phase",
    "description": "Timber wall formwork drawings for a water treatment plant upgrade: pour phases, panel and waler schedules, waterstops and a formwork BIM model.",
    "canonical": "https://formworkforconcrete.com/projects/fm-woods-wtp-wall-formwork/",
    "ogTitle": "F.M. Woods WTP Upgrades",
    "ogDescription": "Timber wall formwork drawings for a water treatment plant upgrade: pour phases, panel and waler schedules, waterstops and a formwork BIM model.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/fm-woods-wtp-wall-formwork/fmw-walls-3d-phase-2-1",
    "h1": "F.M. Woods WTP Upgrades",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/fm-woods-wtp-wall-formwork/fmw-walls-3d-phase-2-1",
      "width": 1200,
      "height": 630,
      "caption": "Braced timber wall forms for a water treatment plant upgrade"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "F.M. Woods WTP Upgrades"
      }
    ]
  },
  "/projects/chemical-storage-feed-system-formwork/": {
    "kind": "project",
    "title": "Chemical Storage Formwork Shop Drawings, Melbourne FL",
    "description": "Formwork shop drawings for a chemical storage area in four pour phases: timber forms, bracing and block-out details, lumber and panel schedules.",
    "canonical": "https://formworkforconcrete.com/projects/chemical-storage-feed-system-formwork/",
    "ogTitle": "Chemical Storage and Feed System",
    "ogDescription": "Formwork shop drawings for a chemical storage area in four pour phases: timber forms, bracing and block-out details, lumber and panel schedules.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/chemical-storage-feed-system-formwork/chem-3d-pour-phases",
    "h1": "Chemical Storage and Feed System",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/chemical-storage-feed-system-formwork/chem-3d-pour-phases",
      "width": 1200,
      "height": 630,
      "caption": "3D views of the four timber formwork pour phases"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Chemical Storage and Feed System"
      }
    ]
  },
  "/projects/uc-davis-equine-center-formwork/": {
    "kind": "project",
    "title": "UC Davis Equine Center Formwork Layouts with Cam-Lock",
    "description": "Timber formwork layouts with Cam-Lock hardware for a treadmill pit, walls and slab edges at the UC Davis Equine Center, with panel and lumber schedules.",
    "canonical": "https://formworkforconcrete.com/projects/uc-davis-equine-center-formwork/",
    "ogTitle": "UC Davis Equine Performance & Rehabilitation Center",
    "ogDescription": "Timber formwork layouts with Cam-Lock hardware for a treadmill pit, walls and slab edges at the UC Davis Equine Center, with panel and lumber schedules.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/uc-davis-equine-center-formwork/ucd-3d-phase-5",
    "h1": "UC Davis Equine Performance & Rehabilitation Center",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/uc-davis-equine-center-formwork/ucd-3d-phase-5",
      "width": 1200,
      "height": 630,
      "caption": "Timber wall forms with Cam-Lock hardware and kicker braces"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "UC Davis Equine Performance & Rehabilitation Center"
      }
    ]
  },
  "/projects/villa-turks-and-caicos-formwork/": {
    "kind": "project",
    "title": "Villa Formwork Drawings and Pour Map, Turks and Caicos",
    "description": "Pour map and timber formwork drawings for a two-storey concrete villa: 14 pours, footings, columns, pool walls and two suspended slab levels.",
    "canonical": "https://formworkforconcrete.com/projects/villa-turks-and-caicos-formwork/",
    "ogTitle": "Villa in Turks and Caicos",
    "ogDescription": "Pour map and timber formwork drawings for a two-storey concrete villa: 14 pours, footings, columns, pool walls and two suspended slab levels.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/villa-turks-and-caicos-formwork/villa-pour-map-overview",
    "h1": "Villa in Turks and Caicos",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/villa-turks-and-caicos-formwork/villa-pour-map-overview",
      "width": 1200,
      "height": 630,
      "caption": "Colour-coded pour map of a two-storey villa"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Villa in Turks and Caicos"
      }
    ]
  },
  "/projects/hungry-horse-slab-shoring/": {
    "kind": "project",
    "title": "Slab and Beam Shoring Layout, Hungry Horse, Montana",
    "description": "Slab and beam formwork in lumber on steel props: lumber plan, props plan, sections and 3D view, with site photos of the shoring as built.",
    "canonical": "https://formworkforconcrete.com/projects/hungry-horse-slab-shoring/",
    "ogTitle": "Slab and Beam Shoring, Hungry Horse, Montana",
    "ogDescription": "Slab and beam formwork in lumber on steel props: lumber plan, props plan, sections and 3D view, with site photos of the shoring as built.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_fill,g_auto,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/hungry-horse-slab-shoring/hh-site-shoring-wide",
    "h1": "Slab and Beam Shoring, Hungry Horse, Montana",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_fill,g_auto,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/hungry-horse-slab-shoring/hh-site-shoring-wide",
      "width": 1200,
      "height": 630,
      "caption": "Steel props and timber beams supporting slab and beam formwork"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "Slab and Beam Shoring, Hungry Horse, Montana"
      }
    ]
  },
  "/projects/oid-paulsell-gate-structures-formwork/": {
    "kind": "project",
    "title": "OID Paulsell Lateral Gate Structure Formwork",
    "description": "Formwork drawings, hardware schedule and BIM model for 14 concrete structures of an irrigation canal expansion for the Oakdale Irrigation District.",
    "canonical": "https://formworkforconcrete.com/projects/oid-paulsell-gate-structures-formwork/",
    "ogTitle": "OID Paulsell Lateral Expansion",
    "ogDescription": "Formwork drawings, hardware schedule and BIM model for 14 concrete structures of an irrigation canal expansion for the Oakdale Irrigation District.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/oid-paulsell-gate-structures-formwork/oid-gs1-3d",
    "h1": "OID Paulsell Lateral Expansion",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/oid-paulsell-gate-structures-formwork/oid-gs1-3d",
      "width": 1200,
      "height": 630,
      "caption": "3D views of the gate structure GS1 formwork"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Projects",
        "path": "/projects/"
      },
      {
        "name": "OID Paulsell Lateral Expansion"
      }
    ]
  },
  "/timber-wall-formwork-ties-walers-bracing/": {
    "kind": "post",
    "title": "Timber Wall Formwork: Ties, Walers and Bracing",
    "description": "How timber wall forms carry concrete pressure, how to space ties and walers, and what a wall formwork drawing should show, with three project examples.",
    "canonical": "https://formworkforconcrete.com/timber-wall-formwork-ties-walers-bracing/",
    "ogTitle": "Timber Wall Formwork: Ties, Walers and Bracing",
    "ogDescription": "How timber wall forms carry concrete pressure, how to space ties and walers, and what a wall formwork drawing should show, with three project examples.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/fm-woods-wtp-wall-formwork/fmw-walls-3d-phase-2-1",
    "h1": "Timber Wall Formwork: Ties, Walers and Bracing",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/fm-woods-wtp-wall-formwork/fmw-walls-3d-phase-2-1",
      "width": 1200,
      "height": 630,
      "caption": "Braced timber wall forms for a water treatment plant upgrade"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Timber Wall Formwork: Ties, Walers and Bracing"
      }
    ],
    "article": {
      "wordCount": 994,
      "keywords": [
        "#Formwork",
        "#FormworkDesign",
        "#WallFormwork",
        "#TimberFormwork",
        "#ShopDrawings",
        "#ConcreteConstruction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/slab-shoring-layout-from-drawing-to-site/": {
    "kind": "post",
    "title": "Slab Shoring Layout: From Drawing to Site",
    "description": "How to lay out slab and beam shoring: deck, joists, beams and props, design loads, prop capacity and what the drawing should show, with site photos.",
    "canonical": "https://formworkforconcrete.com/slab-shoring-layout-from-drawing-to-site/",
    "ogTitle": "Slab Shoring Layout: From Drawing to Site",
    "ogDescription": "How to lay out slab and beam shoring: deck, joists, beams and props, design loads, prop capacity and what the drawing should show, with site photos.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_fill,g_auto,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/hungry-horse-slab-shoring/hh-site-shoring-wide",
    "h1": "Slab Shoring Layout: From Drawing to Site",
    "published": "2026-10-08T09:00:00+00:00",
    "modified": "2026-10-08T09:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_fill,g_auto,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/hungry-horse-slab-shoring/hh-site-shoring-wide",
      "width": 1200,
      "height": 630,
      "caption": "Steel props and timber beams supporting slab and beam formwork"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Slab Shoring Layout: From Drawing to Site"
      }
    ],
    "article": {
      "wordCount": 761,
      "keywords": [
        "#Formwork",
        "#FormworkDesign",
        "#SlabFormwork",
        "#Shoring",
        "#ShopDrawings",
        "#ConcreteConstruction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  },
  "/footing-and-foundation-formwork-typical-details/": {
    "kind": "post",
    "title": "Footing and Foundation Formwork: Typical Details",
    "description": "Typical footing, slab edge and foundation box formwork details from real projects, where footing forms go wrong, and what the drawing should show.",
    "canonical": "https://formworkforconcrete.com/footing-and-foundation-formwork-typical-details/",
    "ogTitle": "Footing and Foundation Formwork: Typical Details",
    "ogDescription": "Typical footing, slab edge and foundation box formwork details from real projects, where footing forms go wrong, and what the drawing should show.",
    "ogImage": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/villa-turks-and-caicos-formwork/villa-footing-3d",
    "h1": "Footing and Foundation Formwork: Typical Details",
    "published": "2026-10-08T15:00:00+00:00",
    "modified": "2026-10-08T15:00:00+00:00",
    "image": {
      "url": "https://res.cloudinary.com/oceanbim/image/upload/c_pad,b_white,w_1200,h_630,f_jpg,q_auto/formworkforconcrete.com/projects/villa-turks-and-caicos-formwork/villa-footing-3d",
      "width": 1200,
      "height": 630,
      "caption": "Typical timber footing form with lumber supports"
    },
    "breadcrumb": [
      {
        "name": "Home",
        "path": "/"
      },
      {
        "name": "Footing and Foundation Formwork: Typical Details"
      }
    ],
    "article": {
      "wordCount": 819,
      "keywords": [
        "#Formwork",
        "#FormworkDesign",
        "#FootingFormwork",
        "#FoundationFormwork",
        "#TimberFormwork",
        "#ConcreteConstruction"
      ],
      "section": [
        "Blog-post"
      ]
    }
  }
};
