#!/usr/bin/env python3
"""One-time content migration: WordPress extract -> files in content/.

Reads extract/ (WP-CLI + rendered HTML, see plans/rebuild-formworkforconcrete-nextjs.md section 1) and the SEO
baseline, and writes:

  content/seo.ts                 title/description/canonical/og/JSON-LD facts of the 20 kept URLs (generated)
  content/projects/<slug>.md     the 11 project pages (frontmatter + body)
  content/posts/<slug>.md        the 5 blog posts (frontmatter + body)

The output is meant to be reviewed and edited by hand afterwards; this script is not part of the build.
Run from the repo root:  python3 scripts/build-content.py
"""
import csv
import html
import importlib.util
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("e2m", ROOT / "scripts" / "elementor-to-md.py")
e2m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(e2m)

SITE = "https://formworkforconcrete.com"
META = json.loads((ROOT / "extract/meta/posts-meta.json").read_text())
BASELINE = {r["url"]: r for r in csv.DictReader(open(ROOT / "seo-baseline/formworkforconcrete.com.pages.csv"))}
JSONLD = json.loads((ROOT / "seo-baseline/formworkforconcrete.com.hreflang-jsonld.json").read_text())["jsonld"]
TAGS = {}
cur = None
for line in (ROOT / "extract/meta/post-tags.txt").read_text().splitlines():
    if line.startswith("## "):
        cur = line[3:].strip()
    elif cur and line.startswith("["):
        TAGS[cur] = json.loads(line)

PROJECT_IDS = ["577", "988237", "988246", "988259", "988270", "988283", "988297", "988574", "988593", "988606", "988619"]
POST_IDS = ["9094", "988769", "988841", "988852", "988872"]
# These two archives are not rebuilt (they redirect to /news/), see section 6 of the plan.
DROPPED = {f"{SITE}/author/pjzadb73wk/", f"{SITE}/category/blog-post/"}

# --- alt text from the rendered pages, for images whose Elementor widget has none --------------------------------
ALT_BY_SRC: dict[str, str] = {}
for f in (ROOT / "extract/html").glob("*.html"):
    for tag in re.findall(r"<img\b[^>]*>", f.read_text(errors="ignore")):
        alt = re.search(r'\balt="([^"]*)"', tag)
        for attr in ("data-lazy-src", "data-src", "src"):
            m = re.search(rf'\b{attr}="(https?://[^"]+)"', tag)
            if m and alt and alt.group(1).strip():
                ALT_BY_SRC.setdefault(m.group(1), html.unescape(alt.group(1)).strip())


def plain(s: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", s or "")).replace("\xa0", " ").strip()


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def alt_for(url: str, widget_alt: str, fallback: str) -> str:
    return (widget_alt or ALT_BY_SRC.get(url) or fallback).strip()


# --- content/seo.ts -----------------------------------------------------------------------------------------------
def seo_entry(url: str) -> dict:
    b = BASELINE[url]
    path = url.replace(SITE, "")
    graph = [n for blk in JSONLD[url] for n in (blk.get("@graph") or [blk])]
    wp = next(n for n in graph if n["@type"] in ("WebPage", "CollectionPage", "ProfilePage"))
    img = next((n for n in graph if n["@type"] == "ImageObject" and n.get("@id", "").endswith("#primaryimage")), None)
    bc = next(n for n in graph if n["@type"] == "BreadcrumbList")
    art = next((n for n in graph if n["@type"] == "Article"), None)
    kind = "home" if path == "/" else "post" if art else "project" if path.startswith("/projects/") and path != "/projects/" else "page"
    entry = {
        "kind": kind,
        "title": b["title"],
        "description": b["meta_description"],
        "canonical": b["canonical"],
        "ogTitle": b["og_title"],
        "ogDescription": b["og_description"],
        "ogImage": b["og_image"],
        "h1": b["h1"],
        "published": wp.get("datePublished", ""),
        "modified": wp.get("dateModified", ""),
        "image": {k: img[k] for k in ("url", "width", "height", "caption") if k in img} if img else None,
        "breadcrumb": [
            {"name": plain(i["name"]), **({"path": i["item"].replace(SITE, "")} if "item" in i else {})} for i in bc["itemListElement"]
        ],
    }
    if art:
        entry["article"] = {"wordCount": art.get("wordCount"), "keywords": art.get("keywords", []), "section": art.get("articleSection", [])}
    return path, entry


def write_seo():
    entries = dict(seo_entry(u) for u in BASELINE if u not in DROPPED)
    ts = (
        "// GENERATED by scripts/build-content.py from seo-baseline/ (the SEO baseline of 2026-10-04). Edit with care:\n"
        "// every value here is what the live WordPress site emits today, and the SEO check compares against it.\n"
        'export type PageKind = "home" | "page" | "project" | "post";\n\n'
        "export interface SeoEntry {\n"
        "  kind: PageKind;\n  title: string;\n  description: string;\n  canonical: string;\n  ogTitle: string;\n  ogDescription: string;\n"
        "  /** Absolute URL, exactly as in the baseline (files under /wp-content/uploads/ ship in public/). */\n  ogImage: string;\n"
        "  h1: string;\n  published: string;\n  modified: string;\n"
        "  /** The primary image of the page, for the JSON-LD graph. */\n"
        "  image: { url: string; width: number; height: number; caption: string } | null;\n"
        "  breadcrumb: { name: string; path?: string }[];\n"
        "  article?: { wordCount: number; keywords: string[]; section: string[] };\n}\n\n"
        f"export const seo: Record<string, SeoEntry> = {json.dumps(entries, indent=2, ensure_ascii=False)};\n"
    )
    (ROOT / "content/seo.ts").write_text(ts)
    print(f"content/seo.ts: {len(entries)} pages")


# --- Markdown bodies ----------------------------------------------------------------------------------------------
def clean_md(s: str) -> str:
    s = s.replace("\xa0", " ").replace("​", "")
    s = re.sub(r"[ \t]+\n", "\n", s)
    return s.strip()


def blocks_to_md(blocks, title: str, img_counter: dict, heading_mode: str) -> tuple[list[str], dict]:
    """heading_mode 'project': every heading becomes ##. 'post': keep the WordPress level."""
    out: list[str] = []
    extra: dict = {}
    i = 0
    while i < len(blocks):
        b = blocks[i]
        kind = b[0]
        if kind == "bg":
            i += 1
            continue
        if kind == "heading":
            level = int(b[2][1]) if re.match(r"h[1-6]", b[2] or "") else 2
            text = plain(b[1])
            if heading_mode == "project":
                level = 2
            out.append("#" * level + " " + text)
        elif kind == "text":
            nxt = blocks[i + 1] if i + 1 < len(blocks) else None
            if nxt and nxt[0] == "button" and heading_mode == "post":
                # Call-to-action: paragraph(s) + "Contact us" button, rendered as a callout.
                para = clean_md(b[1])
                lines = [f"> {p}" if p else ">" for p in para.split("\n")]
                lines.append(">")
                lines.append('> [Contact us](/contact-us/#contact-form "button")')
                out.append("\n".join(lines))
                i += 1  # the button is consumed
            else:
                out.append(clean_md(b[1]))
        elif kind == "image":
            img_counter["n"] += 1
            alt = alt_for(b[1], b[2], f"{title}: formwork drawing {img_counter['n']}")
            url = b[1].replace("http://formworkforconcrete.com", "https://formworkforconcrete.com")
            out.append(f"![{alt.replace(']', ')').replace('[', '(')}]({url})")
        elif kind == "button":
            if heading_mode == "post":
                out.append('[Contact us](/contact-us/#contact-form "button")')
            else:
                extra["moreProjects"] = True
        elif kind == "label":
            extra["tags"] = [t.strip() for t in b[1].split("/")]
        i += 1
    return out, extra


def write_projects():
    (ROOT / "content/projects").mkdir(parents=True, exist_ok=True)
    for pid in PROJECT_IDS:
        m = META[pid]
        slug = m["slug"]
        title = plain(m["title"])
        blocks = e2m.blocks(str(ROOT / f"extract/elementor/{pid}.json"))
        # EXPERTISE band and the final call-to-action are part of the page template, not of each project.
        body_blocks = []
        skip = False
        for b in blocks:
            if b[0] == "heading" and plain(b[1]).upper() == "EXPERTISE":
                skip = True
            if b[0] == "bg" and skip:
                continue
            if skip and b[0] in ("text",):
                continue
            if skip and b[0] == "heading" and plain(b[1]).upper() != "EXPERTISE":
                skip = False
            if skip:
                continue
            body_blocks.append(b)
        out, extra = blocks_to_md(body_blocks, title, {"n": 0}, "project")
        thumb = m["thumb"]
        fm = [
            "---",
            f"title: {yaml_str(title)}",
            f"excerpt: {yaml_str(m['excerpt'].replace(chr(13), ''))}",
            f"cover: {yaml_str(thumb['url'])}",
            f"coverAlt: {yaml_str(thumb['alt'] or title)}",
        ]
        if extra.get("tags"):
            fm.append("tags: " + json.dumps(extra["tags"], ensure_ascii=False))
        if extra.get("moreProjects"):
            fm.append("moreProjects: true")
        fm.append("---\n")
        (ROOT / f"content/projects/{slug}.md").write_text("\n".join(fm) + "\n\n".join(out) + "\n")
        print(f"content/projects/{slug}.md")


def write_posts():
    (ROOT / "content/posts").mkdir(parents=True, exist_ok=True)
    for pid in POST_IDS:
        m = META[pid]
        slug = m["slug"]
        title = plain(m["title"])
        blocks = e2m.blocks(str(ROOT / f"extract/elementor/{pid}.json"))
        out, _ = blocks_to_md(blocks, title, {"n": 0}, "post")
        thumb = m["thumb"]
        fm = [
            "---",
            f"title: {yaml_str(title)}",
            f"date: {m['date'][:10]}",
            f"category: {yaml_str((m['categories'] or ['Blog-post'])[0])}",
            f"cover: {yaml_str(thumb['url'])}",
            f"coverAlt: {yaml_str(thumb['alt'] or title)}",
            "tags: " + json.dumps(TAGS.get(pid, []), ensure_ascii=False),
            "---\n",
        ]
        (ROOT / f"content/posts/{slug}.md").write_text("\n".join(fm) + "\n\n".join(out) + "\n")
        print(f"content/posts/{slug}.md")


def write_alt_map():
    (ROOT / "extract/meta/alt-by-src.json").write_text(json.dumps(ALT_BY_SRC, indent=1, ensure_ascii=False))


if __name__ == "__main__":
    write_alt_map()
    write_seo()
    write_projects()
    write_posts()
