#!/usr/bin/env node
// Turns content/media-manifest.csv into content/media.generated.ts: a typed registry of every Cloudinary
// asset the site uses. The key is the old WordPress/Cloudinary URL (what the copy still contains), the value
// the public id in the new cloud. Run after scripts/upload-media.mjs (the `prebuild` script runs it too).
import fs from 'node:fs';
import path from 'node:path';
import { readManifest, root } from './media-lib.mjs';

const rows = readManifest().filter((r) => r.cloudinary_public_id).sort((a, b) => a.old_url.localeCompare(b.old_url));
const body = rows
  .map((r) => {
    const svg = /\.svg(\?|$)/i.test(r.old_url);
    return `  ${JSON.stringify(r.old_url)}: { id: ${JSON.stringify(r.cloudinary_public_id)}, w: ${Number(r.width) || 0}, h: ${Number(r.height) || 0}${svg ? ', svg: true' : ''}${r.alt ? `, alt: ${JSON.stringify(r.alt)}` : ''} },`;
  })
  .join('\n');

const out = `// GENERATED by scripts/gen-media.mjs from content/media-manifest.csv. Do not edit.
export interface MediaAsset { id: string; w: number; h: number; svg?: boolean; alt?: string }

export const mediaAssets = {
${body}
} as const satisfies Record<string, MediaAsset>;

export type MediaUrl = keyof typeof mediaAssets;
`;
fs.writeFileSync(path.join(root, 'content', 'media.generated.ts'), out);
console.log(`content/media.generated.ts: ${rows.length} assets`);
